# Generated by Django 5.0.4 on 2024-05-02 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': '商品カテゴリ',
                'verbose_name_plural': '商品カテゴリ',
            },
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': ('商品',), 'verbose_name_plural': '商品'},
        ),
    ]
